analysis:
  default_lookback_days: 20
  indicators:
    atr_period: 14
    macd_fast: 12
    macd_signal: 9
    macd_slow: 26
    rsi_period: 14
    volume_ma_period: 20
  min_volatility_threshold: 0.02
  min_volume_threshold: 1000000
  support_resistance:
    min_touches: 2
    tolerance: 1.0    # 增加容忍度，更容易聚类支撑阻力位
    window: 5         # 减小窗口，更容易识别局部高低点
app:
  language: zh_CN
  log_level: INFO
  name: US Stock Intraday Arbitrage Assistant
  timezone: America/New_York
data:
  cache:
    history_ttl: 3600
    indicators_ttl: 300
    price_ttl: 60
  fallback_sources:
  - alpha_vantage
  - finnhub
  primary_source: yfinance
  rate_limits:
    requests_per_hour: 5000
    requests_per_minute: 300
database:
  backup:
    enabled: true
    frequency: daily
    path: backups/
    retention_days: 30
  path: data/trading_assistant.db
  type: sqlite
logging:
  files:
    errors: logs/errors.log
    main: logs/trading_assistant.log
    trades: logs/trades.log
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
  rotation:
    backup_count: 5
    max_size: 10MB
monitoring:
  extended_hours:
    aftermarket_end: '20:00'
    enabled: false
    premarket_start: 04:00
  market_hours_only: true
  trading_hours:
    end: '16:00'
    start: 09:30
    timezone: America/New_York
  update_interval: 300
notifications:
  channels:
    console: true
    email: false
    file: true
    webhook: false
  enabled: true
  types:
  - high_confidence_signals
  - stop_loss_triggered
  - daily_summary
  - system_errors
performance:
  batch_size: 10
  concurrent_analysis: 3
  max_workers: 4
  memory_limit: 500MB
scheduler:
  enabled: true
  max_daily_calls: 7000  # Yahoo Finance允许8000次/天，保留1000次缓冲
  max_hourly_calls: 300   # Yahoo Finance允许360次/小时，保留60次缓冲
  max_minute_calls: 50    # Yahoo Finance允许60次/分钟，保留10次缓冲
  update_interval: 300
  watchlist:
  - AMD
  - PONY
risk:
  default_max_position_pct: 0.15
  default_stop_loss_pct: 0.02
  default_take_profit_pct: 0.05
  emergency_cash_reserve: 0.05
  loss_pause_hours: 2
  max_consecutive_losses: 3
  max_daily_trades: 10
  max_total_exposure: 0.8
  max_trades_per_stock: 3
signals:
  filters:
    rsi_bounds:
    - 20
    - 80
    trend_confirmation: true
    volume_confirmation: true
  max_signals_per_analysis: 5
  min_confidence: 0.6
  signal_expiry_minutes: 30
test:
  demo_value: 123
  value: test_config_value
updated: '2024-12-19'
version: 1.0.0
